# Generated by Django 3.1.1 on 2020-09-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BggGame',
            fields=[
                ('bggid', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('rank', models.IntegerField(null=True)),
                ('min_players', models.IntegerField(null=True)),
                ('max_players', models.IntegerField(null=True)),
                ('min_playtime', models.IntegerField(null=True)),
                ('max_playtime', models.IntegerField(null=True)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('badges', models.ManyToManyField(blank=True, default=None, to='api.Badge')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_checkin', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_checkout', models.DateTimeField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bgggame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_withdrawn', models.DateTimeField(auto_now_add=True)),
                ('date_returned', models.DateTimeField(blank=True, default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.librarygame')),
                ('requisitor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='UsedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('date_checkin', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_checkout', models.DateTimeField(blank=True, default=None, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bgggame')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='librarygame',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player'),
        ),
    ]
