# Generated by Django 3.1.5 on 2021-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgggame',
            name='other_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='bgggame',
            name='bggid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bgggame',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
