# Generated by Django 3.1.2 on 2020-10-12 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201012_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarygame',
            name='date_checkin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usedgame',
            name='date_checkin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date_withdrawn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
