# Generated by Django 3.1.2 on 2020-11-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201120_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Location',
        ),
    ]
