# Generated by Django 3.2.8 on 2022-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_auto_20220310_2232"),
    ]

    operations = [
        migrations.AddField(
            model_name="storegame",
            name="discount_price",
            field=models.FloatField(default=0.0),
        ),
    ]
