# Generated by Django 3.2.8 on 2022-03-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_storegame_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgggame",
            name="year",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
    ]
