# Generated by Django 3.1.4 on 2020-12-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='website',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
