# Generated by Django 3.2.15 on 2022-08-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
