# Generated by Django 3.2.15 on 2022-09-23 17:56

import backend.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image_url', models.ImageField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
    ]
