# Generated by Django 3.2.15 on 2022-09-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220923_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
