# Generated by Django 3.2.16 on 2022-11-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_auto_20221110_2111"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ticketsBuyoutStart",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
