# Generated by Django 3.2.16 on 2022-11-10 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_rename_ticketsbuyoutstart_event_tickets"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("limit", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="tickets",
            field=models.OneToOneField(
                blank=True,
                null=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.eventticket",
            ),
        ),
    ]
