# Generated by Django 3.2.16 on 2022-11-10 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_auto_20221110_2210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tickets",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.eventticket"
            ),
        ),
    ]
