# Generated by Django 3.2.16 on 2022-12-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_paymentmethod"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="description",
            new_name="value",
        ),
    ]
