# Generated by Django 3.2.16 on 2023-02-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_description_paymentmethod_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=20)),
                ("url", models.URLField()),
            ],
        ),
    ]
