# Generated by Django 3.2.16 on 2022-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_auto_20221110_2219"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="validFrom",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="validUntil",
            field=models.DateTimeField(),
        ),
    ]
