# Generated by Django 3.2.16 on 2023-03-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_productticket_is_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productticket",
            name="is_sent",
        ),
        migrations.AddField(
            model_name="order",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
