# Generated by Django 3.2.16 on 2022-11-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_auto_20221114_2256"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tickets",
        ),
        migrations.DeleteModel(
            name="TicketUser",
        ),
    ]
