# Generated by Django 3.2.16 on 2023-03-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_auto_20230303_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
