# Generated by Django 3.2.16 on 2023-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_order_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgggame",
            name="weight",
            field=models.FloatField(null=True),
        ),
    ]
