# Generated by Django 3.2.16 on 2022-11-20 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_order_product_productticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
    ]
