# Generated by Django 3.2.16 on 2023-03-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_bgggame_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="bgggame",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
