# Generated by Django 3.2.16 on 2023-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_bgggame_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
