# Generated by Django 3.2.16 on 2022-11-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_remove_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
